name: brain-music-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - statsmodels
  - jupyter
  - ipykernel
  - ipywidgets
  - tqdm
  - pyyaml
  - joblib
  - pip:
    - xgboost
    - lightgbm
    - catboost
    - pandas-profiling
    - great-expectations
    - mlflow
    - python-dotenv
    - click
    - pillow
    - opencv-python
